### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by Kuchenm0nster** [moso/shade-ghost-theme#2]
Tried to use your theme but can't get the syntax highlighting to work.
>npm install
and 
>gulp
>[15:01:12] Using gulpfile  ~/Ghost/content/themes/shade-ghost-theme/gulpfile.js
>[15:01:12] Starting 'default'...
>[15:01:12] Finished 'default' after 37 ms
but the whole text appears in yellow.

**Comment by moso** [comment]
@Kuchenm0nster: Have you specified the language you want to highlight? The syntax highlight is done by [PrismJS](https://prismjs.com) - check their docs and examples on how to use it.

**Comment by moso** [comment]
@Kuchenm0nster I'm actually very sorry. I have now confirmed what you said. I've made sure PrismJS is included in `default.hbs`, and made sure the layout looks correct before pushing up.

It's fixed in [5091e88](https://github.com/moso/shade-ghost-theme/commit/5091e88b2919594b7d210293520747e71715a70f) if you want to see.

If you want to syntax highlight, eg, HTML you just need to use this markup:
```
    ```html
    <div>
        <p>Hello</p>
    </div>
    ```
```
